<p class="copyright">
Copyright © 2017 the Contributors to the WADG0001/May2017, published by the <a href="https://www.w3.org/community/web-api-discovery">W3 WebAPI Discovery Community Group</a> under the <a href="http://www.w3.org/community/about/agreements/cla/">W3C Community Contributor License Agreement (CLA)</a>. A human-readable <a href="http://www.w3.org/community/about/agreements/cla-deed/">summary</a> is available.
</p>

<a href=http://www.w3.org/><img alt=W3C height=48 src=http://www.w3.org/Icons/w3c_home width=72></a>
<pre class='metadata'>
Title: WADG0001 WebAPI type extension
H1: Version 0.3.0
Date: 2017-05-03
Shortname: wadg0001
Level: 1
Status: w3c/CG-DRAFT
Group: w3c
URL: https://webapi-discovery.github.io/rfcs/rfc0001.html
Editor: Mike Ralphson, Mermade Software
Editor: Ivan Goncharov, APIs.guru
Repository: webapi-discovery/rfcs
Abstract: It is proposed to create an extension to the <a href="https://schema.org/">Schema.Org</a> <a href="https://pending.schema.org/WebAPI">WebAPI</a> type to facilitate better automatic discovery of WebAPIs and associated machine- and human-readable documentation.
Markup Shorthands: css no, markdown yes
Ignored Terms: h1, h2, h3, h4, h5, h6, xmp
</pre>

<pre class=biblio>
{
	"OpenAPI": {
		"title": "OpenAPI Specification v3.0.0-RC1",
		"href": "https://github.com/OAI/OpenAPI-Specification"
	},
	"RAML": {
		"title": "RAML 1.0",
		"href": "https://github.com/raml-org/raml-spec/blob/master/versions/raml-10/raml-10.md"
	},
	"API-Blueprint": {
		"title": "API Blueprint",
		"href": "https://apiblueprint.org"
	},
	"JSON-home": {
		"title": "JSON-home",
		"href": "https://tools.ietf.org/html/draft-nottingham-json-home-06"
	},
	"apis.json": {
		"title": "apis.json",
		"href": "http://apisjson.org/format/apisjson_0.15.txt"
	},
	"semver": {
		"title": "Semantic Versioning 2.0.0",
		"href": "https://semver.org/"
	}
}
</pre>

<p style="display:none" class="copyright" data-fill-with="copyright"></p>

This draft report is the work of the <a href="https://www.w3.org/community/web-api-discovery/">W3 WebAPI Discovery Community Group</a>

<p>This report was published by the <a href="https://www.w3.org/community/web-api-discovery">W3 WebAPI Discovery Community Group</a>. It is not a W3C Standard nor is it on the W3C Standards Track. Please note that under the <a href="http://www.w3.org/community/about/agreements/cla/">W3C Community Contributor License Agreement (CLA)</a> there is a limited opt-out and other conditions apply. Learn more about <a href="http://www.w3.org/community/">W3C Community and Business Groups</a>.</p>

This extension has been created based on real-world use of metadata in the [[OpenAPI]], [[RAML]], [[API-Blueprint]], [[JSON-home]] and [[apis.json]] specifications.

Definitions
===========

<dfn>Machine-readable API Definition</dfn> a structured document defining the inputs and outputs of an API in a standardised format, primarily designed for automated processing, not human consumption.

<div class="note">Note: See <a href="http://nordicapis.com/difference-api-documentation-specification-definition/">this article</a> for an explanation of the difference between API documentation, specifications and definitions.</div>

Proposed Extension
==================

The base <a href="https://schema.org">Schema.org</a> <a href="https://pending.schema.org">WebAPI</a> type, for example:

```json
{
  "@context": "http://schema.org/",
  "@type": "WebAPI",
  "name": "Google Knowledge Graph Search API",
  "description": "The Knowledge Graph Search API lets you find entities in the Google Knowledge Graph. The API uses standard schema.org types and is compliant with the JSON-LD specification.",
  "documentation": "https://developers.google.com/knowledge-graph/",
  "termsOfService": "https://developers.google.com/knowledge-graph/terms",
  "provider": {
    "@type": "Organization",
    "name": "Google Inc."
  }
}
```

is to be extended as follows:

The extension properties (and their types) are:
* versions (OPTIONAL array of <a href="https://schema.org/Thing">Thing</a> -> <a href="http://meta.schema.org/Property">Property</a> -> <a href="http://schema.org/softwareVersion">softwareVersion</a>). It is RECOMMENDED that APIs be versioned using [[semver]]
* entryPoints (OPTIONAL array of <a href="https://schema.org/Thing">Thing</a> -> <a href="https://schema.org/Intangible">Intangible</a> -> <a href="https://schema.org/EntryPoint">EntryPoint</a>)
      * extended with: responseContentTypes (OPTIONAL <a href="http://schema.org/Text">Text</a>)
* license (OPTIONAL, <a href="http://schema.org/CreativeWork">CreativeWork</a> or <a href="http://schema.org/URL">URL</a>) - the license for the design/signature of the API
* transport (enumerated <a href="http://schema.org/Text">Text</a>: HTTP, HTTPS, SMTP,  MQTT, WS, WSS etc)
* apiProtocol (OPTIONAL, enumerated <a href="http://schema.org/Text">Text</a>:  SOAP, GraphQL, gRPC, Hydra, JSON API, XML-RPC, JSON-RPC etc)
* webApiDefinitions (OPTIONAL array of <a href="http://schema.org/EntryPoint">EntryPoint</a>s) containing links to <a>machine-readable API definition</a>s
* webApiActions (OPTIONAL array of potential <a href="http://schema.org/Action">Action</a>s)

The Content-Type(s) consumed by the WebAPI MAY be included in the <a href="http://schema.org/EntryPoint">EntryPoint</a>.<a href="http://schema.org/contentType">contentType</a> property. The Content-Type(s) produced by the WebAPI MAY be included in the <a href="http://schema.org/EntryPoint">EntryPoint</a>.responseContentType property.

Content-Types
-------------

The webApiDefinitions (<a href="http://schema.org/EntryPoint">EntryPoint</a>) <a href="http://schema.org/contentType">contentType</a> property MUST contain the singular contentType relevant to the API description format used. It is RECOMMENDED that <a href="https://iana.org">IANA</a>-registered contentTypes be used. The following non-IANA contentTypes MAY additionally be used:

<table class=data>
<thead>
<tr>
<th>Format
<th>Content-Type
<tbody>
<tr><td>OpenAPI / Swagger in JSON<td>application/openapi+json or application/x-openapi+json
<tr><td>OpenAPI / Swagger in YAML<td>application/openapi+json or application/x-openapi+json
<tr><td>RAML<td>application/raml+yaml
<tr><td>API Blueprint in markdown<td>text/vnd.apiblueprint
<tr><td>API Blueprint parsed in JSON<td>application/vnd.refract.parse-result+json
<tr><td>API Blueprint parsed in YAML<td>application/vnd.refract.parse-result+yaml
</tbody>
</table>

Other content-Types such as <b>application/ld+json</b>, <b>application/json</b>, <b>text/markdown</b> etc MAY be used, with decreasing levels of machine-readability. The webApiDefinition (<a href="https://schema.org/EntryPoint">EntryPoint</a>) encodingType property MAY also be specified.

webApiActions
-------------

Valid <a href="https://schema.org/Action">Action</a>.<a href="https://schema.org/name">name</a>s for webApiActions are:

<table class=data>
<thead>
<tr>
<th>Name
<th>Description
<tbody>
<tr><td>apiAuthentication <td> Links to a resource detailing authentication requirements. Note this is a human-readable resource, not an authentication endpoint
<tr><td>apiClientRegistration <td> Links to a resource where a client may register to use the API
<tr><td>apiConsole <td> Links to an interactive console where API calls may be tested
<tr><td>apiPayment <td> Links to a resource detailing pricing details of the API
</tbody>
</table>

Example
=======

A fuller example of a WebAPI annotation, including the extension attributes. Note the @type name is still to be determined.

```json
{
  "@context": "http://schema.org/",
  "@type": "ActionableWebAPI",
  "name": "Google Knowledge Graph Search API",
  "description": "The Knowledge Graph Search API lets you find entities in the Google Knowledge Graph. The API uses standard schema.org types and is compliant with the JSON-LD specification.",
  "documentation": "https://developers.google.com/knowledge-graph/",
  "termsOfService": "https://developers.google.com/knowledge-graph/terms",
  "logo": "https://www.google.com/images/branding/googlelogo/2x/googlelogo_color_272x92dp.png",
  "license": "https://creativecommons.org/licenses/by/3.0/",
  "provider": {
    "@type": "Organization",
    "name": "Google Inc.",
    "contactPoint": [
      {
        "@type": "ContactPoint",
        "name": "Google",
        "url": "https://google.com"
      }
    ],
  },
  "versions": [
    "1.0.0"
  ],
  "entryPoints": [
    {
      "@type": "EntryPoint",
      "url": "https://kgsearch.googleapis.com/",
      "contentType": "application/json",
      "responseContentTypes": "application/json"
    }
  ],
  "transport": "HTTP",
  "apiProtocol": "JSON API",
  "webApiDefinitions": [
    {
      "@type": "EntryPoint",
      "contentType": "application/json",
      "url": "https://kgsearch.googleapis.com/$discovery/rest?version=v1"
    },
    {
      "@type": "EntryPoint",
      "contentType": "application/openapi+json",
      "url": "https://api.apis.guru/v2/specs/googleapis.com/kgsearch/v1/swagger.json"
    },
  ],
  "webApiActions": [
    {
      "@type": "ConsumeAction",
      "name": "apiAuthentication",
      "target": "https://developers.google.com/knowledge-graph/how-tos/authorizing"
    }
  ]
}
```

